site_name: test-cookiecutter
repo_url: https://github.com/RoninD/test-cookiecutter
site_url: https://RoninD.github.io/test-cookiecutter
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Roland Wolman
edit_uri: edit/main/docs/
repo_name: RoninD/test-cookiecutter
copyright: Maintained by <a href="https://RoninD.com">RoninD</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/test_cookiecutter"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoninD/test-cookiecutter
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/test-cookiecutter

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
